import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  blueprint: [
    {
      type: 'category',
      label: 'Blueprint',
      collapsible: false,
      link: {
        type: 'generated-index',
        slug: '/blueprint',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'blueprint',
        },
      ],
    },
  ],
  spec: [
    {
      type: 'category',
      label: 'Spec',
      collapsible: false,
      link: {
        type: 'generated-index',
        slug: 'spec',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'spec',
        },
      ],
    },
  ],
  qa: [
    {
      type: 'category',
      label: 'Quality Assurance',
      collapsible: false,
      link: {
        type: 'generated-index',
        slug: 'qa',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'qa',
        },
      ],
    },
  ],
  onboarding: [
    {
      type: 'category',
      label: 'Onboarding',
      collapsible: false,
      link: {
        type: 'generated-index',
        slug: '/onboarding',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'docs/onboarding',
        },
      ],
    },
  ],
  handbook: [
    {
      type: 'category',
      label: 'Handbook',
      collapsible: false,
      link: {
        type: 'generated-index',
        slug: '/handbook',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'docs/handbook',
        },
      ],
    },
  ],
};

export default sidebars;
