const sidebars = {
  specs: [
    {
      type: 'category',
      label: 'Specs',
      link: {
        type: 'generated-index',
        title: 'Specifications',
        slug: 'specs',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'specs',
        },
      ],
    },
  ],
  design: [
    {
      type: 'category',
      label: 'Design',
      link: {
        type: 'generated-index',
        title: 'Design',
        slug: 'design',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'design',
        },
      ],
    },
  ],
  api: [
    {
      type: 'category',
      label: 'API',
      link: {
        type: 'generated-index',
        title: 'API Reference',
        slug: 'api',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'api',
        },
      ],
    },
  ],
  devGuide: [
    {
      type: 'category',
      label: 'Developer Guide',
      link: {
        type: 'generated-index',
        title: 'Developer Guide',
        slug: 'developer-guide',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'developer-guide',
        },
      ],
    },
  ],
  userGuide: [
    {
      type: 'category',
      label: 'User Guide',
      link: {
        type: 'generated-index',
        title: 'User Guide',
        slug: 'user-guide',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'user-guide',
        },
      ],
    },
  ],
  project: [
    {
      type: 'category',
      label: 'Project',
      link: {
        type: 'generated-index',
        title: 'Project Management',
        slug: 'project',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'project',
        },
      ],
    },
  ],
  changelog: [
    {
      type: 'category',
      label: "What's New",
      link: {
        type: 'generated-index',
        title: "What's New",
        slug: 'changelog',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'changelog',
        },
      ],
    },
  ],
};

export default sidebars;
