import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  blueprint: [
    {
      type: 'autogenerated',
      dirName: 'blueprint',
    },
  ],
  specs: [
    {
      type: 'autogenerated',
      dirName: 'spec',
    },
  ],
  quality: [
    {
      type: 'autogenerated',
      dirName: 'quality',
    },
  ],
  onboarding: [
    {
      type: 'category',
      label: 'Onboarding',
      items: [
        {
          type: 'autogenerated',
          dirName: 'docs/onboarding',
        },
      ],
    },
  ],
  handbook: [
    {
      type: 'category',
      label: 'Handbook',
      items: [
        {
          type: 'autogenerated',
          dirName: 'docs/handbook',
        },
      ],
    },
  ],
};

export default sidebars;
