const sidebars = {
  specs: [
    {
      type: 'category',
      label: 'Specifications',
      link: {
        type: 'generated-index',
        title: 'Specifications',
        description:
          'Tài liệu đặc tả yêu cầu, kiến trúc và chức năng của hệ thống.',
        slug: '/specs',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'specs',
        },
      ],
    },
  ],
  design: [
    {
      type: 'category',
      label: 'Design System',
      link: {
        type: 'generated-index',
        title: 'Design System',
        description: 'Quy định về UI, UX và Design Tokens.',
        slug: '/design',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'design',
        },
      ],
    },
  ],
  api: [
    {
      type: 'category',
      label: 'API Reference',
      link: {
        type: 'generated-index',
        title: 'API Reference',
        description: 'Tài liệu đặc tả API Contracts và OpenAPI Specification.',
        slug: '/api',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'api',
        },
      ],
    },
  ],
  devGuide: [
    {
      type: 'category',
      label: 'Developer Guide',
      link: {
        type: 'generated-index',
        title: 'Developer Guide',
        description: 'Hướng dẫn cài đặt, phát triển và đóng góp cho dự án.',
        slug: '/developer-guide',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'developer-guide',
        },
      ],
    },
  ],
  userGuide: [
    {
      type: 'category',
      label: 'User Guide',
      link: {
        type: 'generated-index',
        title: 'User Guide',
        description:
          'Hướng dẫn sử dụng các tính năng của hệ thống cho từng đối tượng người dùng.',
        slug: '/user-guide',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'user-guide',
        },
      ],
    },
  ],
  project: [
    {
      type: 'category',
      label: 'Project Information',
      link: {
        type: 'generated-index',
        title: 'Project Information',
        description:
          'Thông tin về quản lý dự án, quy trình và đội ngũ phát triển.',
        slug: '/project',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'project',
        },
      ],
    },
  ],
  changelog: [
    {
      type: 'category',
      label: 'Changelog',
      link: {
        type: 'generated-index',
        title: 'Changelog',
        description: 'Lịch sử thay đổi và cập nhật của dự án.',
        slug: '/changelog',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'changelog',
        },
      ],
    },
  ],
};

export default sidebars;
