const sidebars = {
  specs: [
    {
      type: 'autogenerated',
      dirName: 'specs',
    },
  ],
  design: [
    {
      type: 'autogenerated',
      dirName: 'design',
    },
  ],
  api: [
    {
      type: 'autogenerated',
      dirName: 'api',
    },
  ],
  devGuide: [
    {
      type: 'autogenerated',
      dirName: 'developer-guide',
    },
  ],
  userGuide: [
    {
      type: 'autogenerated',
      dirName: 'user-guide',
    },
  ],
  project: [
    {
      type: 'autogenerated',
      dirName: 'project',
    },
  ],
  changelog: [
    {
      type: 'autogenerated',
      dirName: 'changelog',
    },
  ],
};

module.exports = sidebars;
