openapi: 3.0.0
info:
  title: LMS API
  version: 1.0.0
  description: API for the LMS platform.
paths:
  /health:
    get:
      summary: Health Check
      responses:
        '200':
          description: OK
