openapi: 3.0.0
info:
  title: LMS API
  version: 1.0.0
  description: "API for the LMS platform. According to System Design SSoT, this REST API is reserved for Health Checks, File Uploads, and Webhooks. All business logic queries and mutations are handled via GraphQL."
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: /api/v1
    description: v1 API Server

tags:
  - name: System
    description: "System utilities like Health Check."
  - name: Media
    description: "File upload and media management."
  - name: Webhooks
    description: "External system integrations."

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    webhookSignature:
      type: apiKey
      in: header
      name: X-LMS-Signature

  schemas:
    # --- Common ---
    Error:
      type: object
      properties:
        code:
          type: string
          description: "Error code (e.g., BAD_REQUEST, UNAUTHORIZED)"
        message:
          type: string
          description: "Detailed error message"

    # --- Media Module Entities (SSoT: content.md) ---
    FileUploadResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        url:
          type: string
        filename:
          type: string
        mimetype:
          type: string
        size:
          type: integer

    # --- Webhook Payloads ---
    PaymentWebhookType:
      type: object
      properties:
        transaction_id: { type: string }
        status: { type: string, enum: [success, failed, pending] }
        amount: { type: integer }
        currency: { type: string }

paths:
  /health:
    get:
      operationId: healthCheck
      summary: Health Check
      description: "Quick check to verify API availability."
      tags: [System]
      security: []
      responses:
        '200':
          description: "System is operational."
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: { type: string, example: "ok" }
                  timestamp: { type: string, format: date-time }

  /upload:
    post:
      operationId: uploadFile
      summary: Upload File
      description: "Upload media files (images, videos, documents). Max size 500MB."
      tags: [Media]
      security: [{ bearerAuth: [] }]
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '201':
          description: "File uploaded successfully."
          content:
            application/json:
              schema: { $ref: '#/components/schemas/FileUploadResponse' }
        '400':
          description: "Invalid file or size limit exceeded."
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Error' }

  /webhooks/payment:
    post:
      operationId: handlePaymentWebhook
      summary: Payment Webhook
      description: "Receive payment status updates from external payment gateway."
      tags: [Webhooks]
      security: [{ webhookSignature: [] }]
      requestBody:
        content:
          application/json:
            schema: { $ref: '#/components/schemas/PaymentWebhookType' }
      responses:
        '200':
          description: "Webhook received and processed."
        '400':
          description: "Invalid signature or payload."
